config/routes.rb
TARS::Application.routes.draw do
  resources :activities do
    resources :preformeds
    collection do
      get 'search'
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :preformed
  attr_accessible :activity, :value
  validates :activity, :presence => true,
                       :uniqueness => true
  validates :value, :presence => true,
                    :numericality => { :only_integer => true }
  has_many :preformeds, :dependent => :destroy
end

app/models/preformed.rb
class Preformed < ActiveRecord::Base
  belongs_to :activity
  attr_accessible :activity, :preformed, :selected_date
  validates :preformed, :presence => true,
                        :numericality => { :only_integer => true }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
    @preformeds = Preformed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    @preformed = @activity.preformed.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  def search
    @activity_search = Activity.search(params[:start_date], params[:end_date], params[:keywords]).order(sort_column + ' ' + sort_direction).paginated_for_index(per_page, page)

    @activity = Activity.new(params[:project])

    respond_to do |format|
      format.html # search.html.erb
      format.json { render :json => @project }
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/preformeds_controller.rb
class PreformedsController < ApplicationController
  def create
    @activity = Activity.find(params[:activity_id])
    @preformed = @activity.preformed.create(params[:preformed])
    redirect_to activity_path(@activity)
  end

  def destroy
    @activity = Activity.find(params[:activity_id])
    @preformed = @activity.preformed.find(params[:id])
    @preformed.destroy
    redirect_to :back
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/preformed_helper.rb
module PreformedHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :activity %><br />
    <%= f.text_field :activity %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>


<%= form_tag search_path, method: :get do %>
  <%= text_field_tag("start_date") %></br>
  <div class="field">
    <%= datepicker_input "activity","start_date" %></br>
  </div>
  <%= text_field_tag("end_date") %></br>
  <div class="field">
    <%= datepicker_input "activity","end_date" %></br>
  </div>

  <%= submit_tag "Search", name: nil %>
<% end %>
<table>
  <tr>
    <th>Activity</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.activity %></td>
    <td><%= activity.value %></td>
    <td>====</td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <tr>
      <td><%= render activity.preformeds %></td>
    </tr>
  </tr>
  <p></p>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Activity:</b>
  <%= @activity.activity %>
</p>

<p>
  <b>Value:</b>
  <%= @activity.value %>
</p>

<%= render @activity.preformeds %>

<%= render "preformeds/form" %>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TARS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/preformeds/_form.html.erb
<%= form_for([@activity, @activity.preformed.build]) do |f| %>
  <div class="field">
    <%= f.label :preformed %><br />
    <%= f.text_field :preformed %>
  </div>
  <div class="field">
    <%= f.label :selected_date %><br />
    <%= f.date_select :selected_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preformeds/_preformed.html.erb
<p>
  <b>Date:</b>
  <%= preformed.selected_date %>
  <b>Preformed:</b>
  <%= link_to preformed.preformed, [preformed.activity, preformed],        :confirm => 'Are you sure you want to delete this value
  ?',
               :method => :delete %>
</p>